[build]
builder = "nixpacks"
buildCommand = "python -m pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn --worker-class gevent --workers 1 --bind 0.0.0.0:$PORT server:app"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"

[env]
PYTHON_VERSION = "3.8.12"
PYTHONUNBUFFERED = "1"
NIXPACKS_PYTHON_VERSION = "3.8.12" 