[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 server:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 
