[build]
builder = "nixpacks"
buildCommand = "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT server:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
PYTHON_VERSION = "3.8.16"
NIXPACKS_PYTHON_VERSION = "3.8.12" 